cache:
  directories:
    - cache
deploy:
  fqdn: www.booksie.org
  github_token:
    secure: lRkXBfUvkuFgjCmAUbz7KxHER5iiF47V5Js8CrZifcIEGD+WcfEtZHQGjUvaCxwtpPJ74ToXHgN/dWUfOV9qqrXJ/Yuz/5dYhDROpOWHfbJ93Qc73r0OuSneC16BqMna2OupVl+23VtPkKvLV7bkxPAUQglTa5ZECHdJ3OyEYZIg4BXqwCbqxDjl7kXpCNgXoDSWB8/7o5AAogmC4X070Hze3zYbowmD5BZNC+vNbDCeOPJgmIERSv7jvGh7T9yeRxc3QmoxGYDypNO9esiAPIT98EBlrSOpO6aMXNtE5ns2JzuM/kxLDydejrOIry05/1oB6aWB8FYanyMvWz2xlgfMShyv+ByhAUtItCBYfUiK9xuNIDWuNyEiDSYaaEfXxeOUiW78YOexuOo1DME+4gv1vfqgpSYpB1Utuv8j1u5leix4sfn/BiZTQlkSbeNJpCIxKZDlaOA4wLIq+oXyCQz+ZCFPDtAf4s3uM/TnU2vv4uuzGjB98GEQnz7Cv98WCZ4gkj0h8luNbCZ4ycreOCc9d3/IjPbm7/YAzMIJgUATK5xzvmLDfyzO1UXfaUPljJSxvcnNgXb28HvCq/IXNdlQrs4uw8vLHJ7j3VT6umMVpb/1fzFhYSvZKPaEPGJRkDZaK1APBhJG5gSfPjcExAhRD3VwDBMfr1FmgI2UUr8=
  local_dir: dist
  provider: pages
  skip_cleanup: true
language: node_js
node_js: node
script: rm -r cache/cat-and-dog && ./build
