deploy:
  fqdn: www.booksie.org
  github_token:
    secure: 1tUOROmrObm7xRvmc7O6iPV/AJYiv5F2CFNAWH6RnmFpyWgx3YdmxGoJkpK2mKtSCGBmVi8mWiniqJrBphb2llyVUTsurBJryvPO+bSlEIzaH7+iJ5KsKXLkLbM31xSAZEZZbIE7tMysC5JWsZSopVtSRf/rdDzmsKJSvrx+DsMiXG1w+GGlvfYyjYQz+uBJrPakmEUnmJTw9+Haub5rptpZzeW2VW11omtdq6YVfl7mZyGzoTTPgw8VrFlMDYwgK2vAQc22mC1OcYQmEz0dBt88JGRfDVBiRlPb/c9gYRKdnkCKkXl4wVr4FQCct/2dJhdE8gz2Wdq8w/hAKS7UGiO3RkNSaDBVtGbFrErhtqEV1gE0ku1y6+ikJhH8Np09npHhDBCLMm6wTPK3ndUqqrbjMflZKJ/+kypTC4EUHqMF1d97SmKrXgL9OWJCT2UHP/TLz7Es4WJclQNWRhGZr/UklvFJsIvpjeTL0HiE2xzNqGKh1Y9Wopr6zixKl0Ce/CyM7lqMhsdPesCDhYIjNOihI8dnHgviI00UblvbVvWCqx/JZjKJw0IQLR603Yqf8t4g/lov+mMcE73J4lFVUaND87xhRpTOOhfzll44g+2GSW9davBiuNWmVUKXgtGaC/2RaS7ccYmBeGWUqyUcDlZxCVnmmoqcDn6fEoIw4VY=
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
language: node_js
node_js: node
script: ./build
