deploy:
  fqdn: www.booksie.org
  github_token:
    secure: CFqjEB8S6owuK9c4ynPsHm7fgQ5xXy5Nr4VJNfxNB707mv+wjHC/+/dAxOKBgEIQihe6muQQynqgMLS+5uW4Mg3JGk8t6S8s+DGBYRdvHGf4B8SXjM2JB6cWKn4Df+hnozFqhRjeE4vO1FCeqsmVlvanzcmt3YC1SjGR5l8QwCe13FDN5qMCA2r6fq3KXChXqfbslvHz5CWREg9wpOeMX002jTLw6NxiCQz8LJFuK2Iy9e2xxwHnkgM6zyDGqqESUMpTjlXdveVInAwBBf16z8GFxPfH6h8dw/6M716ZM/xr7jIhOAMTv8UdXhxwRAWsrCvzWrbVOyzfqjiaYCeq6vXh5DnJYBplYDWtgEoI9KeayvUTcnMxy6edIqBgQdJeIsvjTo5CAni2yrwntCAS5JBqmr1ahjRZKsM0vdI5fOj9esNsPECco5hZvCQSjFXvVEeKjGrj7Dd3E3hj+3yQA6ktB7p95T06hmuS/XQkggaa+uZBN1lL3qFrY7S8B9CrF4QmfauFCETD50gW8s5nyMI9g2Eb6bF9eCjreChwTA2MYjNY/su0Yaks1uqioXXN0LvQFSmqwYZPy9AIfh9KRS2OAAdOSOwZvQ9slkG4bLm56xoo8ZvY0MwqXABEBj7lUy2y8Lgekj/BM0254klwZuuagyTJVmRoZlJiIt/KI7k=
  on:
    branch: master
  provider: pages
  skip_cleanup: true
language: node_js
node_js: node
script: echo TODO
